name: youtube_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_echarts: ^2.4.0 
  mrx_charts: ^0.1.3
  audio_wave: ^0.1.4
  charts_painter: ^2.0.0+2
  pie_chart: ^5.3.2
  graphic: 0.10.6
  charts_flutter: 0.12.0
  intl: 0.17.0 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
    flutter_map:
        git:
            url: https://github.com/fleaflet/flutter_map.git
            # ref: main 

flutter: 
  uses-material-design: true

